### ISSUE TITLE
How about adding req to the method give more flexibility for the use cases

### ISSUE THREAD

**Issue by maheshyamsani** [LionC/express-basic-auth#16]
https://github.com/LionC/express-basic-auth/blob/738ef5bf2cb6ea2389467fa6d9cce345ab4319e2/index.js#L45

if(isAsync)
            return authorizer(authentication.name, authentication.pass, authorizerCallback,req)
        else if(!authorizer(authentication.name, authentication.pass))
            return unauthorized()

**Comment by willemevenwel** [comment]
Any luck on accessing the req object within the authorizer method?

**Comment by yonilerner** [comment]
I, too, would like to see this functionality. Accepting PRs?

**Comment by willemevenwel** [comment]
I did a little bit of reading. It seems as tho the authentication is fired prior to delivery of the request object. This means the request object is not yet sent/available.

Possible work around is to NOT use basic auth, and parse your own authentication parameters in the body of the request payload. Then configure some kind of middleware that fires to authenticate before actually executing the request/route.

**Comment by LionC** [comment]
Sorry for the late reply - I am still in the process of rewriting in typescript before releasing new features. Passing `req` will be one of them. @yonilerner I will accept PRs once that is done and I have a contributors agreement in place.

I will close this for now, thanks for the elaborate answers @yonilerner !

**Comment by tahpot** [comment]
Any update on this?
