### ISSUE TITLE
Blank page in safari when pw contains !

### ISSUE THREAD

**Issue by sandersdevelopments** [LionC/express-basic-auth#46]
Funny Story 🙂 

app.use(basicAuth({
    users: { 'admin': 'supersecret' }
}))

When the supersecret contains an exclamation mark Safari shows a blank page 🙂 question marks for example work. 
The issue does not appear on any android Version but on every ios Version ^^ maybe the internal base64 is messed up by special special characters?

**Comment by LionC** [comment]
Can not reproduce with other clients, so this seems to be a safari issue. Please comment again if you have indication that this is actually a server side problem.
