### ISSUE TITLE
Add login request on authorizer

### ISSUE THREAD

**Issue by ViniMnzs** [LionC/express-basic-auth#55]
I need to setup a login request with axios as authentication method inside the express-basic-auth, to access my swagger. Is it possible? How can I do it? I tried with authorizer, but failed.

example:

`app.use(['/${SWAGGER_API_PATH}'], basicAuth({ authorizer: myAuthorizer }));`
`                  `
`function myAuthorizer(username, password) {`
`  const response = axios.post('http://localhost:3000/api/auth', {username, password});`

`  if(response.status === 200){`
`	return true;`
`  };`
`  else{`
`	return false;`
`  }`
`};`

**Comment by LionC** [comment]
Check the readme on [how to do asynchronous authorizers](https://github.com/LionC/express-basic-auth#custom-async-authorization).
