### ISSUE TITLE
Authorization without data, just press "cancel"

### ISSUE THREAD

**Issue by dyurashevichLT** [LionC/express-basic-auth#59]
press cancel and you will get access
<img width="1027" alt="image" src="https://user-images.githubusercontent.com/112411101/220572460-6044a31c-1c42-4803-859d-3b3f08b5e498.png">

My example
<img width="823" alt="image" src="https://user-images.githubusercontent.com/112411101/220572715-c1532092-278b-48f0-91af-de17dffa7523.png">

**Comment by LionC** [comment]
Order of middleware matters, if you want `express-basic-auth` to gate the serving of content, you need to put it before the part that serves the content, not after.
