### ISSUE TITLE
Challenge: true

### ISSUE THREAD

**Issue by Upperstage** [LionC/express-basic-auth#7]
I cannot get my custom authorizer to work without setting challenge to true.  When challenge is not true, all requests fail with a 401.
  
It appears when basic-auth fails, the code goes to the unauthorized method without looking for a custom authorizer.

**Comment by LionC** [comment]
Hi Upperstage, can you give me a working example for me to reproduce the problem? I would really like to fix it!

**Comment by LionC** [comment]
Closing for now, as it is not possible to reproduce.
